name: Get baby swim class availablity data

on:
  push:
    paths:
      - .github/workflows/swim-class-check.yaml 
      - postprocess.ts
  workflow_dispatch: 
  schedule:
    - cron: '*/10 * * * *' 

jobs:
  # scheduled:
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Check out repo
  #       uses: actions/checkout@v3
  #     - name: Setup deno
  #       uses: denoland/setup-deno@main
  #       with:
  #         deno-version: v1.x     
  #     - name: Fetch data 
  #       uses: githubocto/flat@v3
  #       with:
  #         http_url: https://yarraleisure.perfectgym.com.au/clientportal2/Groups/GroupDetailsModal/Details?groupId=6462
  #         downloaded_filename: swim-class.json 
  #         postprocess: postprocess.ts
